# Generated by Django 4.1.4 on 2022-12-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotel_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
