# Generated by Django 4.1.4 on 2022-12-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_comment_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
