# Generated by Django 4.1.4 on 2022-12-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
