# Generated by Django 4.1.4 on 2022-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
    ]
