# Generated by Django 4.1.4 on 2022-12-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_comment_comment_comment_email_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='uptade_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='mesaj',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
