# Generated by Django 4.1.2 on 2022-12-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
